backend:
  name: openai
  params:
    api_key: !ENV ${OPENAI_API_KEY}
    # ChatGPT
    model: gpt-3.5-turbo
    # GPT-4
    # model: gpt-4
    temperature: 0.9

router:
  plugins:
    # For https://github.com/artmatsak/chatgpt-todo-plugin/
    # - localhost:5002
    - www.klarna.com

horace:
  # Any extra instructions to prepend the prompt with
  extra_instructions: >-
    You are a helpful and polite AI assistant.
  # extra_instructions: >-
  #   In your speech, you impersonate Jedi Master Yoda and crack jokes in response
  #   to mentions of other Star Wars characters.
  max_validation_retries: 3